### ISSUE TITLE
List

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#1]
## Value Proposition
- As a user
- I want to have a list of Restaurants 
- in order to have a overview of the restaurants what they findet
## Description

![Image](https://user-images.githubusercontent.com/123362292/227465348-81e4acce-0a31-44fc-9482-6ac1252a28a1.png)

## Acceptance criteria
- [ ] The "Restaurant " displayed above the restaurant list
- [ ] Link at top-left corner links to the homepage
- [ ] Shows one photo of each restaurant 
- [ ] The name, Cuisine and Rating are displayed below the photo. they and photo should be in on card
- [ ] The list is scrollable

## Tasks
- [ ] Create a branch
- [ ] Global styled
- [ ] Create "db.js" with Restaurants
- [ ] Save the photos in "images" folder and put it in "public" folder
- [ ] Create components/Card
- [ ] Create components/Nav
- [ ] Create components/Head
- [ ] Add page pages/restaurants
- [ ] Write tests

**Comment by LuYujin9** [comment]
close
