### ISSUE TITLE
Backend and update of the Reserve-Page

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#16]
## Value Proposition

**As a** user  
**I want to** save my data in cloud  
**so that** I can get my data from different devices. 
​

## Description

![backend](https://user-images.githubusercontent.com/123362292/231196681-e2aa28bd-a96f-469a-bb99-d7645c022c09.png)

​

## Acceptance Criteria

- [ ] all websites download the data from data bank
- [ ] when some one reserved, the data of reserve will be added in data bank
- [ ] after reserving the "remainingSeats" in "restaurants" collection will be also updated
- [ ] when some one clicked favorite button, the "isFavorite" in "users" collection will be updated
- [ ] after reserving a message will be showed in a pop-up window
      ​

## Tasks
     

- [ ] create a data base "lecker-map" with 3 collections : "restaurants", "users" and  "reserves"
- [ ] deleted the functions for local storage
- [ ] write the schema for  "restaurant", "user" and "reserve" in "db/models" folder
- [ ] write the connect  in "db" folder
- [ ] write the api for "restaurants", "user-infos" and "reserves".
- [ ] update the functions for setting or storing "isFavorite" and "reserve" data
- [ ] add the component "MessageModal" and use it in "pages/restaurant/reserve/[id]"
- [ ] deleted the "pages/restaurant/reserve/reserveMessage"
