### ISSUE TITLE
handle my comments

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#17]
## Value Proposition

**As a** user
**I want to** see all my comments and delete or edit my comments
**so that**  I can handle my comments better and I can revise them when I changed my mind

## Description

![handle my comments](https://user-images.githubusercontent.com/123362292/232996062-5a4c31d3-94a8-4f1a-9480-51b6a0d1e873.png)

​

## Acceptance Criteria

- [ ] there is a link in My-Data-Page to My-Comments-Page
- [ ] in the My-Comments-Page all comments from this user should be showed
- [ ] there is a "Ändern"button and a "Delete" button in every comment list item
- [ ] when user clicks the delete button, this comment will be delete, and not show anymore in this page
- [ ] when user clicks the "Ändern" button, 
- the comment disappeared 
- a form with "Abschicken"button shows in this list item
- the comment context is in the input 
- user kann click "Abschicken" button to save the changed
- after clicking "Abschicken" button, the form will disappear and the comment shows there
- [ ] in Details-Page
- the comments from the user show also with  a "Ändern"button and a "Delete"
- the functions of these button are the same as in My-Comments-Page

## Tasks

- [ ] update the component/CommentItem
- [ ] updated the My-Data-Page
- [ ] created the My-Comments-Page
- [ ] update the test of component/CommentItem
- [ ] styled
