### ISSUE TITLE
edit the reserve

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#18]
## Value Proposition

**As a** user
**I want to** edit or cancel my reserves  
**so that** when something changed, I can also update my reserves. 
​

## Description

![edit the reserves](https://user-images.githubusercontent.com/123362292/231825565-cb94b61e-5590-4eb8-8b2e-4926cbfc6f56.png)

​

## Acceptance Criteria

- [ ] there are a "Stornieren" button in every reserve
- [ ] when "Stornieren" button is clicked, the reserve will be canceled. the list of reserves will be renewed.
- [ ] there is a "Ändern" button in every reserve 
- [ ] when "Ändern" button is clicked, it will be link to Edit-My-Reserves-Page. 
- [ ] there is a form in Edit-My-Reserves-Page, the original infos of this reserve will be there
- [ ] the number of "Personen" can only less than the number in the note over the form
- [ ] after submitting the page, the infos of reserve in the form will be renewed
- [ ] at the same time a pop-up window will be showed 
- [ ] in the pop-up window, there are a  link to My-Reserves-Page and a button to close the window
      ​

## Tasks

- [ ] update the pages/my-data/reserves
- [ ] create a /pages/my-data/reserves/[id]
- [ ] write the utils to reuse some functions
- [ ] style the pages
- [ ] write the test

**Comment by PReichetanz** [comment]
I really like the idea!
I would only suggest to split this user story into two: (1) edit and (2) delete. This way, you make sure to make progress with focusing on one specific topic instead of doing two things at once.
