### ISSUE TITLE
search and filter

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#19]
## Value Proposition

**As a** user 
**I want to** search  the restaurant  
**so that**  I can easier find out, which restaurant I would like to reservieren
​

## Description
![search and filter](https://user-images.githubusercontent.com/123362292/232390035-e5019566-331a-4b8d-adb1-0f96971efa74.png)

​

## Acceptance Criteria

- [ ] there is a form in homepage 
- [ ] if the user wants, er can give some conditions in the input
- [ ] it is not necessary to give condition in every input
- [ ] after clicking the button "Senden"
-  when there are eligible restaurants , it should link to the List-Page and show these restaurants
-  when there isn't eligible restaurant, a error message will be showed
- [ ] there ist a filter in the top of List-Page. 
- [ ] after clicking the filter, a list of conditions should be showed
- [ ] after choosing one condition, the order of restaurants list will be changed 
- [ ] the context of filter will be changed to current condition
      ​

## Tasks

- [ ] create a component/SearchForm
- [ ] update  pages/index with SearchForm
- [ ] update the functions in pages/restaurants
- [ ] write the function of filter
- [ ] style the pages and compnent
- [ ] write the test

**Comment by rabe200** [comment]
lgtm ,
 just some small thing(s): 
1) for the value proposition: change the german "reservieren" for "reserve" :)

2) "the inputs are not required":
it isn't completely clear to me if the input field is not required or if the input doesn't need to be filled for the form to be submitted?

**Comment by LuYujin9** [comment]
Thanks. I updated my user story.

**Comment by FrankSiyli** [comment]
LGTM just a hint for a better user experience. When the user search input doesn't fit to any location you could give 3 random restaurants with a message "no hits but maybe here is something else for you" instead of just give an alert.
