### ISSUE TITLE
Details of one restaurant

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#2]
## Value Proposition
- As a user
- I want to details of one restaurant 
- in order to know more informations of each restaurant

## Description

![details](https://user-images.githubusercontent.com/123362292/228474836-f8b219ec-ef96-485e-9f17-15bb1cb5d691.png)

## Acceptance criteria
on screen 1: 
- [x] the photo of each restaurant should link to the details page

on screen 2: 
- [x] display a link to menu , a photo, the description and comments 
- [x] the head is the name of this restaurant
- [x] the page  is scrollable
- [x] a button shows unter a comment when it's more than 3 rows lang.
- [x] the button can expand or collapse the comment

on screen 3: 
- [x] the button should toggle icon

## Tasks
- [x] Update components/List with a link
- [x] Create components/CommentCard
- [x] Create components/CommentsList
- [x] Create components/Album
- [x] create page pages/restaurants/[id]
- [x] style the Comments and pages
- [x] Write tests

**Comment by PReichetanz** [comment]
Nice work! Does the "Direkt reservieren" button do anything? If not, consider removing it for now and implement it later.
