### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#22]
## Value Proposition

**As a** user
**I want to** log in my name  
**so that** I can save my data unter my name.

 
​

## Description

![log-in](https://user-images.githubusercontent.com/123362292/232278097-53c8b7a6-579d-450a-9970-7d224c5c9a93.png)

​

## Acceptance Criteria

when user hasn't given a user name:
- [ ] no matter er open which page, shows alway at first a pop-up log-in window
- [ ] there isn't button to close this pop-up window
- [ ] there is a input box and a button in this window
- [ ] the user should give a user name here and clicks the button to close this window
when user has logged in:
- [ ] there is a button in the right of all heading
- [ ] user can click the button and call the log-in pop-up window out
- [ ] in this window shows the current user name
- [ ] after writing a new user name and sending, the user name changes
- [ ] there is a close-button in the up right of the window
- [ ] clicking the close-button can close this window

      ​

## Tasks

- [ ] write a component/LoginModal
- [ ] add a props "username" and lift down to all pages
- [ ] updated the component Heading
- [ ] update the functions for bookmark button and reserves
- [ ] update the schema Reserve and User with "username"
- [ ] write test 
- [ ] style

**Comment by PReichetanz** [comment]
Very nice work!

However, these are two user stories: start with the login page and create a hardcoded user who can log in (maybe two for testing).
Changing the user name should be a different user story.

**Comment by LuYujin9** [comment]
Thanks Paul. I wrote only one user story, because I would like to use only one component. I changed some of the acceptance criteria
