### ISSUE TITLE
update Detail-Page  with more informations and function to comment

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#25]
## Value Proposition

**As a** user
**I want to** comment in the page of a restaurant
**so that** to share the experience in this restaurant
​

## Description

![comment in detail-page](https://user-images.githubusercontent.com/123362292/232428429-be4426e3-7f92-4189-a037-a37c7d666ad8.png)

## Acceptance Criteria

- [ ] the address and telephone number should be in Detail-Page 
- [ ] there is a form with button in this page
- [ ] user can write something and send
- [ ] the new comment will be in the top of comments list.
      ​

## Tasks

- [ ] update the data bank 
- [ ] create a component/CommentForm
- [ ] update the Detail-Page
- [ ] style
- [ ] write the test
