### ISSUE TITLE
map with pins

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#26]
## Value Proposition

**As a** user
**I want to** I want to view a map featuring pins indicating the restaurants I have visited,
**so that** enabling me to keep track of my past visits and their locations.
​

## Description

​
![map-page](https://user-images.githubusercontent.com/123362292/232430531-6684153c-017d-463d-8462-cc881143e2bd.png)

## Acceptance Criteria

- [ ] when user reserved one restaurant, the location of this restaurant will be showed as a pin
- [ ] when user click a pin, the name of restaurant will be showed
- [ ] the more restaurants the user hat been to, the more pins will be showed
- [ ] the map can be zoom in und zoom out
      ​

## Tasks

- [ ] create pages/map
- [ ] update component/Footer with link to Map-Page
- [ ] styled

**Comment by LuYujin9** [comment]
That is much better, thank you.
