### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#3]
##Bookmark

## Value Proposition
- As a user
- I want to bookmark restaurants 
- in order to finde my favorite ones easier

## Description

![Image](https://user-images.githubusercontent.com/123362292/227466419-621f897f-2e00-408f-bb62-f365e055162b.png)

## Acceptance criteria
- [ ] Buttons should toggle with color
- [ ] Link at bottom should link to the "Meine Data" Page
- [ ] Link at top-left corner links to last page  
- [ ] on screen 2: a Buttons link to the " Favoriten" Page
- [ ] on screen 3: show a list of favorite Restaurants
     - the format is the same as list in User Story 1
     - the buttons can be clicked 
     - after the clicking, the card of restaurant should be invisible.

## Tasks
- [ ] Create components/BookmarkButton  and put it in pages
- [ ] Update components/Card
- [ ] Update components/Nav
- [ ] Update components/Head
- [ ] Add pages pages/my-data and pages/my-data/Favoriten
- [ ] Write tests

**Comment by PReichetanz** [comment]
Hi Jin, 

nice work!

Two thoughts:
- I don't think that you actually need the `my-data` page right now, because it does not really show anything except a link to the favourites page, but I guess you can keep it this way.
- the page should have the name `my-data/favorites` instead of `my-data/Favoriten`

**Comment by LuYujin9** [comment]
> **Acceptance Criteria** "Link at top-left corner links to last page" when does this appear? Is it always visible?
Good question. My plan is, when the back button in the first page in one tab(e.g. my-data), it is invisible.

Thanks for your advise, I update the tasks. 😀

**Comment by LuYujin9** [comment]
> Hi Jin,
> 
> nice work!
> 
> Two thoughts:
> 
> * I don't think that you actually need the `my-data` page right now, because it does not really show anything except a link to the favourites page, but I guess you can keep it this way.
> * the page should have the name `my-data/favorites` instead of `my-data/Favoriten`

Thanks for you suggestions. You are right, actually the my-data page can be a  separate user story.

**Comment by alinawinter** [comment]
Looks really cool!! :-) I have nothing to add :-)
