### ISSUE TITLE
Update Remaining-Seats-Filter

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#30]
## Value Proposition

**As a** user
**I want to** see the remaining seats and don't click the button
**so that** use the reserve function easier

## Description

![update-remaining-seats-filter](https://user-images.githubusercontent.com/123362292/233619120-44f668bc-079c-4469-a62a-e3e43d9d5ea9.png)

​

## Acceptance Criteria

- [ ] after both inputs are selected, a message will be showed
      ​

## Tasks

- [ ] update the SearchRemainingSeatsFilter
- [ ] update the test
- [ ] style
