### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#6]
## Value Proposition

**As a**  user  
**I want to** have a look of menu,
**so that** I can have a look if there is anything I would like to eat.
​

## Description
![menu](https://user-images.githubusercontent.com/123362292/229111715-b4477361-ed17-4849-a6f5-3a10a1d81f59.png)

## Acceptance Criteria

screen 1 : 
- [x] the Link on the top links to the "menu" page (screen 2).

screen 2 : 
- [x] the informations of Foods should be shown in this page
- [x] the informations include the name, the description and price.
- [x] a background photo should be there
- [x] this page is scrollable. ​
- [x] when there is no menu from the restaurant, this page will shows "Tut mir leid! Es gibt noch keine Speisekarte."

## Tasks

- [x] update the data.js of the restaurant with informations of foods 
- [x] create compnents/FoodCard 
- [x] create pages/restaurants/menu/[id] 
- [x] write the test for FoodCard
- [x] styled these pages

**Comment by supernova-97** [comment]
Looks good! Very useful feature what I'm missing when I'm looking for restaurants
