### ISSUE TITLE
reserve

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#8]
## Value Proposition

**As a** user
**I want to** simply link to the reserve page, when he browse a restaurant
**so that**  when he likes the restaurant, they can directly reserve a table
​

## Description
![reserve](https://user-images.githubusercontent.com/123362292/229818804-cf19c0f8-cdb8-41a7-a0dd-a2dd0c333376.png)

​

## Acceptance Criteria

- [x] a button link to the reserving page. It will be put in the 2 details pages of each Restaurant

screen 1 : 
- [x] in reserving page, user can choose the data and time to see, how many seats are still remained. The User can only choose the date today or after today.
- [x] after searching. It shows the remaining seats.
- [x] people can write how many seats he wants. When it's more than remaining seats, the reserve can't be send.
- [ ] the name, phone number and email can be filled in this page. Name and phone number are required. 

screen 2:
- [ ]  after reserving, the page automatically jumps to an another page to show the result of reserving.

## Tasks
- [ ] create  /pages/restaurants/reserve/index.js
- [ ] create  /pages/restaurants/reserve/[id].js
- [ ] create components/toReservePageButton with the link, which links to reserving Page
- [ ] create components/ReserveForm with input and form
- [ ] create components/remainingSeatsFilter with input and form
- [ ] styled
- [ ] write the test for ReserveForm

**Comment by LuYujin9** [comment]
Thanks, Melissa.  
I should add the description, when the user choose "how many people", the `<select>` shows only how many seat left in this restaurant.
