### ISSUE TITLE
My-Data-Page and links to Favorites-Page

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/capstone-project#9]
## Value Proposition

**As a** user 
**I want to** see a page  
**so that** I can link to the page, which shows my favorite restaurants 
​

## Description
![my-data and favorites](https://user-images.githubusercontent.com/123362292/228815784-ec6319bd-17ec-4103-8f2c-4dcf6ab9998d.png)

​

## Acceptance Criteria

screen 1:
- [ ] this My-Data-Page should be showed, wenn the button in the right of the footer is clicked.
- [ ] wenn the My-Data-Button is clicked, it link to homepage.
- [ ] there a Heading in the page, and shows "Meine Datei"
- [ ] the button "Meine Favoriten" link to Favorites-Page.

screen 2: 
- [ ] there is a Heading in the page, and shows "Favoriten"
- [ ] the button in the right of "Favoriten" is back-button, it links back to My-Data-Page.
- [ ] the footer is the same as screen 1
      ​

## Tasks

- [ ] create pages/my-data/index
- [ ] create pages/my-data/favorites
- [ ] update components/Navbar, add a link mit icon to my-data-page
